{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-api-app.fullname" . }}-secrets
data:
  hfToken: {{ .Values.secret.hfToken | b64enc }}
type: Opaque
{{- end -}}