apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-api-app.fullname" . }}
  labels:
    {{- include "model-api-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "model-api-app.selectorLabels" . | nindent 4 }}
