name: "build and push docker container images"
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      image-name:
        type: string
        required: true
      image-tag:
        type: string
        required: true
      docker-file-path: 
        type: string
        required: false

jobs:
  docker-build-model-download-container:
    uses: afrozsh19/githubWorkflows/.github/workflows/main-docker-push.yaml@main
    secrets: inherit
    with:
      image-name: llm-model-download-container
      image-tag: v0.0.1
      docker-file-path: predownload-script 

  docker-build-model-service-fast-api:
    uses: afrozsh19/githubWorkflows/.github/workflows/main-docker-push.yaml@main
    secrets: inherit
    with:
      image-name: model-serving-fastapi
      image-tag: v0.0.1
      docker-file-path: model_inference

